version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION:-v2.3.0}
    container_name: nacos-server
    environment:
      # 运行模式
      - MODE=${MODE:-standalone}
      # 数据库配置
      - SPRING_DATASOURCE_PLATFORM=${SPRING_DATASOURCE_PLATFORM:-embedded}
      # MySQL 配置 (当使用外部数据库时)
      - MYSQL_SERVICE_HOST=${MYSQL_SERVICE_HOST:-}
      - MYSQL_SERVICE_PORT=${MYSQL_SERVICE_PORT:-3306}
      - MYSQL_SERVICE_DB_NAME=${MYSQL_SERVICE_DB_NAME:-nacos}
      - MYSQL_SERVICE_USER=${MYSQL_SERVICE_USER:-nacos}
      - MYSQL_SERVICE_PASSWORD=${MYSQL_SERVICE_PASSWORD:-nacos}
      # JVM参数
      - JVM_XMS=${JVM_XMS:-256m}
      - JVM_XMX=${JVM_XMX:-256m}
      - JVM_XMN=${JVM_XMN:-128m}
      # 认证配置
      - NACOS_AUTH_ENABLE=${NACOS_AUTH_ENABLE:-true}
      - NACOS_AUTH_TOKEN=${NACOS_AUTH_TOKEN:-SecretKey012345678901234567890123456789012345678901234567890123456789}
      - NACOS_AUTH_IDENTITY_KEY=${NACOS_AUTH_IDENTITY_KEY:-nacos}
      - NACOS_AUTH_IDENTITY_VALUE=${NACOS_AUTH_IDENTITY_VALUE:-nacos}
      # 控制台配置
      - NACOS_AUTH_CACHE_ENABLE=false
    ports:
      - "${NACOS_SERVER_PORT:-8848}:8848"
      - "${NACOS_GRPC_PORT:-9848}:9848"
      - "${NACOS_GRPC_SERVER_PORT:-9849}:9849"
    volumes:
      - ./data:/home/nacos/data
      - ./logs:/home/nacos/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/v1/console/health/readiness"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - nacos-network

networks:
  nacos-network:
    driver: bridge

volumes:
  nacos-data:
  nacos-logs: